select * from notifications
select * from notification_settings
select * from operation_types
select * from reagent_categories
select * from reagent_operations
select * from reagent_receipts
select * from reagents
select * from suppliers
select * from users
select * from work_schedule